[package]
name = "voxel_remesh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.1.0"
glib = "0.1.0"
gtk = "0.1.0"